-- ============================================================
-- JobPulse AI — Seed Data
-- Inserts the core skill dictionary into the skills table.
--
-- This is reference seed data. Full job data is loaded via the
-- Python pipeline (scripts/run_pipeline.py).
-- ============================================================

INSERT INTO skills (skill_id, skill_name, skill_category)
VALUES
    ('Python', 'Python', 'Programming'),
    ('R', 'R', 'Programming'),
    ('Java', 'Java', 'Programming'),
    ('Scala', 'Scala', 'Programming'),
    ('SQL', 'SQL', 'Programming'),
    ('JavaScript', 'JavaScript', 'Programming'),
    ('C++', 'C++', 'Programming'),
    ('C#', 'C#', 'Programming'),
    ('Go', 'Go', 'Programming'),
    ('Shell', 'Shell', 'Programming'),
    ('MySQL', 'MySQL', 'Databases'),
    ('PostgreSQL', 'PostgreSQL', 'Databases'),
    ('SQL Server', 'SQL Server', 'Databases'),
    ('MongoDB', 'MongoDB', 'Databases'),
    ('Redis', 'Redis', 'Databases'),
    ('Cassandra', 'Cassandra', 'Databases'),
    ('Oracle', 'Oracle', 'Databases'),
    ('Elasticsearch', 'Elasticsearch', 'Databases'),
    ('Snowflake', 'Snowflake', 'Databases'),
    ('BigQuery', 'BigQuery', 'Databases'),
    ('SQLite', 'SQLite', 'Databases'),
    ('Power BI', 'Power BI', 'Visualization'),
    ('Tableau', 'Tableau', 'Visualization'),
    ('Excel', 'Excel', 'Visualization'),
    ('Looker', 'Looker', 'Visualization'),
    ('Qlik', 'Qlik', 'Visualization'),
    ('D3.js', 'D3.js', 'Visualization'),
    ('Matplotlib', 'Matplotlib', 'Visualization'),
    ('Seaborn', 'Seaborn', 'Visualization'),
    ('Plotly', 'Plotly', 'Visualization'),
    ('AWS', 'AWS', 'Cloud'),
    ('Azure', 'Azure', 'Cloud'),
    ('GCP', 'GCP', 'Cloud'),
    ('Spark', 'Spark', 'Data Engineering'),
    ('Hadoop', 'Hadoop', 'Data Engineering'),
    ('Airflow', 'Airflow', 'Data Engineering'),
    ('Kafka', 'Kafka', 'Data Engineering'),
    ('NiFi', 'NiFi', 'Data Engineering'),
    ('DBT', 'DBT', 'Data Engineering'),
    ('Fivetran', 'Fivetran', 'Data Engineering'),
    ('Scikit-learn', 'Scikit-learn', 'Machine Learning'),
    ('TensorFlow', 'TensorFlow', 'Machine Learning'),
    ('PyTorch', 'PyTorch', 'Machine Learning'),
    ('XGBoost', 'XGBoost', 'Machine Learning'),
    ('LightGBM', 'LightGBM', 'Machine Learning'),
    ('ONNX', 'ONNX', 'Machine Learning'),
    ('Hugging Face', 'Hugging Face', 'Machine Learning'),
    ('NLP', 'NLP', 'Machine Learning'),
    ('Computer Vision', 'Computer Vision', 'Machine Learning'),
    ('Pandas', 'Pandas', 'Data Analysis'),
    ('NumPy', 'NumPy', 'Data Analysis'),
    ('Statistics', 'Statistics', 'Data Analysis'),
    ('Data Cleaning', 'Data Cleaning', 'Data Analysis'),
    ('Data Visualization', 'Data Visualization', 'Data Analysis'),
    ('A/B Testing', 'A/B Testing', 'Data Analysis'),
    ('Time Series', 'Time Series', 'Data Analysis'),
    ('Docker', 'Docker', 'DevOps'),
    ('Kubernetes', 'Kubernetes', 'DevOps'),
    ('Git', 'Git', 'DevOps'),
    ('CI/CD', 'CI/CD', 'DevOps'),
    ('Terraform', 'Terraform', 'DevOps'),
    ('Ansible', 'Ansible', 'DevOps'),
    ('API', 'API', 'Other'),
    ('Microservices', 'Microservices', 'Other'),
    ('Agile', 'Agile', 'Other'),
    ('JIRA', 'JIRA', 'Other'),
    ('Confluence', 'Confluence', 'Other'),
    ('Hive', 'Hive', 'Big Data'),
    ('Presto', 'Presto', 'Big Data')
ON CONFLICT (skill_id) DO NOTHING;